/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTodayRouteImport } from './routes/_authenticated/today'
import { Route as AuthenticatedLocationsRouteImport } from './routes/_authenticated/locations'
import { Route as AuthenticatedResolutionsIndexRouteImport } from './routes/_authenticated/resolutions.index'
import { Route as AuthenticatedRelationshipsIndexRouteImport } from './routes/_authenticated/relationships.index'
import { Route as AuthenticatedEngagementsIndexRouteImport } from './routes/_authenticated/engagements.index'
import { Route as AuthenticatedResolutionsIdRouteImport } from './routes/_authenticated/resolutions.$id'
import { Route as AuthenticatedRelationshipsIdRouteImport } from './routes/_authenticated/relationships.$id'
import { Route as AuthenticatedEngagementsIdRouteImport } from './routes/_authenticated/engagements.$id'
import { Route as AuthenticatedContactsIdRouteImport } from './routes/_authenticated/contacts.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTodayRoute = AuthenticatedTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLocationsRoute = AuthenticatedLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResolutionsIndexRoute =
  AuthenticatedResolutionsIndexRouteImport.update({
    id: '/resolutions/',
    path: '/resolutions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRelationshipsIndexRoute =
  AuthenticatedRelationshipsIndexRouteImport.update({
    id: '/relationships/',
    path: '/relationships/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEngagementsIndexRoute =
  AuthenticatedEngagementsIndexRouteImport.update({
    id: '/engagements/',
    path: '/engagements/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResolutionsIdRoute =
  AuthenticatedResolutionsIdRouteImport.update({
    id: '/resolutions/$id',
    path: '/resolutions/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRelationshipsIdRoute =
  AuthenticatedRelationshipsIdRouteImport.update({
    id: '/relationships/$id',
    path: '/relationships/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEngagementsIdRoute =
  AuthenticatedEngagementsIdRouteImport.update({
    id: '/engagements/$id',
    path: '/engagements/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContactsIdRoute = AuthenticatedContactsIdRouteImport.update({
  id: '/contacts/$id',
  path: '/contacts/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/locations': typeof AuthenticatedLocationsRoute
  '/today': typeof AuthenticatedTodayRoute
  '/contacts/$id': typeof AuthenticatedContactsIdRoute
  '/engagements/$id': typeof AuthenticatedEngagementsIdRoute
  '/relationships/$id': typeof AuthenticatedRelationshipsIdRoute
  '/resolutions/$id': typeof AuthenticatedResolutionsIdRoute
  '/engagements/': typeof AuthenticatedEngagementsIndexRoute
  '/relationships/': typeof AuthenticatedRelationshipsIndexRoute
  '/resolutions/': typeof AuthenticatedResolutionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/locations': typeof AuthenticatedLocationsRoute
  '/today': typeof AuthenticatedTodayRoute
  '/contacts/$id': typeof AuthenticatedContactsIdRoute
  '/engagements/$id': typeof AuthenticatedEngagementsIdRoute
  '/relationships/$id': typeof AuthenticatedRelationshipsIdRoute
  '/resolutions/$id': typeof AuthenticatedResolutionsIdRoute
  '/engagements': typeof AuthenticatedEngagementsIndexRoute
  '/relationships': typeof AuthenticatedRelationshipsIndexRoute
  '/resolutions': typeof AuthenticatedResolutionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/locations': typeof AuthenticatedLocationsRoute
  '/_authenticated/today': typeof AuthenticatedTodayRoute
  '/_authenticated/contacts/$id': typeof AuthenticatedContactsIdRoute
  '/_authenticated/engagements/$id': typeof AuthenticatedEngagementsIdRoute
  '/_authenticated/relationships/$id': typeof AuthenticatedRelationshipsIdRoute
  '/_authenticated/resolutions/$id': typeof AuthenticatedResolutionsIdRoute
  '/_authenticated/engagements/': typeof AuthenticatedEngagementsIndexRoute
  '/_authenticated/relationships/': typeof AuthenticatedRelationshipsIndexRoute
  '/_authenticated/resolutions/': typeof AuthenticatedResolutionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/locations'
    | '/today'
    | '/contacts/$id'
    | '/engagements/$id'
    | '/relationships/$id'
    | '/resolutions/$id'
    | '/engagements/'
    | '/relationships/'
    | '/resolutions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/locations'
    | '/today'
    | '/contacts/$id'
    | '/engagements/$id'
    | '/relationships/$id'
    | '/resolutions/$id'
    | '/engagements'
    | '/relationships'
    | '/resolutions'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/locations'
    | '/_authenticated/today'
    | '/_authenticated/contacts/$id'
    | '/_authenticated/engagements/$id'
    | '/_authenticated/relationships/$id'
    | '/_authenticated/resolutions/$id'
    | '/_authenticated/engagements/'
    | '/_authenticated/relationships/'
    | '/_authenticated/resolutions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/today': {
      id: '/_authenticated/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof AuthenticatedTodayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/locations': {
      id: '/_authenticated/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof AuthenticatedLocationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resolutions/': {
      id: '/_authenticated/resolutions/'
      path: '/resolutions'
      fullPath: '/resolutions/'
      preLoaderRoute: typeof AuthenticatedResolutionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relationships/': {
      id: '/_authenticated/relationships/'
      path: '/relationships'
      fullPath: '/relationships/'
      preLoaderRoute: typeof AuthenticatedRelationshipsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/engagements/': {
      id: '/_authenticated/engagements/'
      path: '/engagements'
      fullPath: '/engagements/'
      preLoaderRoute: typeof AuthenticatedEngagementsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resolutions/$id': {
      id: '/_authenticated/resolutions/$id'
      path: '/resolutions/$id'
      fullPath: '/resolutions/$id'
      preLoaderRoute: typeof AuthenticatedResolutionsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relationships/$id': {
      id: '/_authenticated/relationships/$id'
      path: '/relationships/$id'
      fullPath: '/relationships/$id'
      preLoaderRoute: typeof AuthenticatedRelationshipsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/engagements/$id': {
      id: '/_authenticated/engagements/$id'
      path: '/engagements/$id'
      fullPath: '/engagements/$id'
      preLoaderRoute: typeof AuthenticatedEngagementsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contacts/$id': {
      id: '/_authenticated/contacts/$id'
      path: '/contacts/$id'
      fullPath: '/contacts/$id'
      preLoaderRoute: typeof AuthenticatedContactsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedLocationsRoute: typeof AuthenticatedLocationsRoute
  AuthenticatedTodayRoute: typeof AuthenticatedTodayRoute
  AuthenticatedContactsIdRoute: typeof AuthenticatedContactsIdRoute
  AuthenticatedEngagementsIdRoute: typeof AuthenticatedEngagementsIdRoute
  AuthenticatedRelationshipsIdRoute: typeof AuthenticatedRelationshipsIdRoute
  AuthenticatedResolutionsIdRoute: typeof AuthenticatedResolutionsIdRoute
  AuthenticatedEngagementsIndexRoute: typeof AuthenticatedEngagementsIndexRoute
  AuthenticatedRelationshipsIndexRoute: typeof AuthenticatedRelationshipsIndexRoute
  AuthenticatedResolutionsIndexRoute: typeof AuthenticatedResolutionsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedLocationsRoute: AuthenticatedLocationsRoute,
  AuthenticatedTodayRoute: AuthenticatedTodayRoute,
  AuthenticatedContactsIdRoute: AuthenticatedContactsIdRoute,
  AuthenticatedEngagementsIdRoute: AuthenticatedEngagementsIdRoute,
  AuthenticatedRelationshipsIdRoute: AuthenticatedRelationshipsIdRoute,
  AuthenticatedResolutionsIdRoute: AuthenticatedResolutionsIdRoute,
  AuthenticatedEngagementsIndexRoute: AuthenticatedEngagementsIndexRoute,
  AuthenticatedRelationshipsIndexRoute: AuthenticatedRelationshipsIndexRoute,
  AuthenticatedResolutionsIndexRoute: AuthenticatedResolutionsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
